DEFAULT_OPENAI_CHAT_MODEL = "gpt-5.5"
DEFAULT_OPENAI_MEMORY_EXTRACT_MODEL = "gpt-5.4-mini"
DEFAULT_OPENAI_MEMORY_QUERY_MODEL = "gpt-5.4"
DEFAULT_OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"

DEFAULT_ANTHROPIC_CHAT_MODEL = "claude-sonnet-4-20250514"

MODEL_PREFIX_OPENAI_GPT55 = "gpt-5.5"
MODEL_PREFIX_OPENAI_GPT54 = "gpt-5.4"
MODEL_SELECTION_PATTERN = (
    f"{MODEL_PREFIX_OPENAI_GPT54}*|{MODEL_PREFIX_OPENAI_GPT55}*"
)
MODEL_SWITCHABLE_PREFIXES = (
    f"{MODEL_PREFIX_OPENAI_GPT54}*, {MODEL_PREFIX_OPENAI_GPT55}*"
)

DEFAULT_APP_COMPLETION_MODEL = DEFAULT_OPENAI_CHAT_MODEL
DEFAULT_AGENT_MODEL = DEFAULT_OPENAI_CHAT_MODEL
DEFAULT_SUBAGENT_MODEL = DEFAULT_OPENAI_CHAT_MODEL
DEFAULT_MEMORY_EXTRACT_MODEL = DEFAULT_OPENAI_MEMORY_EXTRACT_MODEL
DEFAULT_MEMORY_QUERY_MODEL = DEFAULT_OPENAI_MEMORY_QUERY_MODEL
DEFAULT_EMBEDDING_MODEL = DEFAULT_OPENAI_EMBEDDING_MODEL

MODEL_EXAMPLES = [
    DEFAULT_OPENAI_CHAT_MODEL,
    "gpt-5.5-pro",
    "gpt-5.5-mini",
    DEFAULT_OPENAI_MEMORY_QUERY_MODEL,
    DEFAULT_OPENAI_MEMORY_EXTRACT_MODEL,
]
